services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: huellas_laravel_app

    ports:
      - "8080:80"

    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8080

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: residencia
      DB_USERNAME: root
      DB_PASSWORD: root

    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:10.4

    container_name: huellas_mysql

    restart: unless-stopped

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: residencia

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: